version: '2'

services:
  blazorapp:
    build:
      context: .
      dockerfile: ./CV.Website/Dockerfile
    hostname: blazorapp
    ports:
      - "8080:80"
    networks:
      - appnetwork
    depends_on:
      - mongodb
      - api
    environment:
      - MONGO_CV=${MONGO_CV}

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "8081:8081"
      - "27017:27017"
    networks:
      - appnetwork
    volumes:
      - ./dbdata:/data/db
    expose: 
      - 27017 

  api:
    build:
      context: .
      dockerfile: ./CV.API/Dockerfile.API
    hostname: api
    ports:
      - "5000:80"
    networks:
      - appnetwork
    depends_on:
      - mongodb
    environment:
      - MONGO_CV=${MONGO_CV}
    expose:
      - 1234

networks:
  appnetwork:
    driver: bridge
